### ISSUE TITLE
/var/run/rsnapshot deleted on reboot

### ISSUE THREAD

**Issue by richardfrankza** [loomsen/puppet-rsnapshot#12]
In debian, contents of /var/run are not persistent and it appears that it is not recreated on reboot.

This means that pids can't be created in /var/run/rsnapshot

**Comment by loomsen** [comment]
Hi @richardfrankza 
You can set `$config_lockpath` to configure the path for PID files.
Cheers.

**Comment by richardfrankza** [comment]
Thanks, just thinking perhaps the config default should be different, but
up to you!

**Comment by loomsen** [comment]
Hmm, good point... I'm going to consider changing it and what impact it might have. Thank you!

**Comment by loomsen** [comment]
Actually, you're right. I'm going to add a tmpfiles.d config to solve the reboot issue.
