### ISSUE TITLE
Function has_key() is deprecated

### ISSUE THREAD

**Issue by hihiuztrewq** [loomsen/puppet-rsnapshot#19]
The function has_key() is deprecated and has been removed in puppetlabs-stdlib >=9

https://github.com/loomsen/puppet-rsnapshot/blob/1b316e2710bee9c753f1dcdc9f8069c4543c15da/manifests/config.pp#L146C8-L146C15

A possible fix is: 
```
-    if has_key($hash, backup_scripts) {
+    if 'backup_scripts' in $hash {

```
(this syntax is possible since Puppet 4)

**Comment by loomsen** [comment]
Hi, thank you for this issue report. Unfortunately, this project is abandoned. Feel free to fork it and create your own version :)
