### ISSUE TITLE
Cron.d files with dots are ignored on debian

### ISSUE THREAD

**Issue by laurigates** [loomsen/puppet-rsnapshot#2]
Cron files under /etc/cron.d are silently ignored for hosts with dots in their name. This seems to be a debian/ubuntu specific issue.

**Comment by loomsen** [comment]
Hi, thank you for reporting this. This is odd, indeed. I will gladly accept patches if you find a way around this :)

**Comment by nickcmaynard** [comment]
If I'm not mistaken, isn't fixing this as simple as replacing line 165 of `config.pp` (https://github.com/loomsen/puppet-rsnapshot/blob/master/manifests/config.pp#L165) with
```
    $cronfile = "${cron_dir}/puppet_rsnapshot"
```

**Comment by loomsen** [comment]
Hi Nick, 

thank you for your suggestion. Unfortunately, this won't work. line 165 is inside a loop, see line 38:
`$hosts_clean.each |String $host, $hash | {`

Where each host has its own cron file. doing like you suggest would result in only one file being written for the last host in question.

**Comment by nickcmaynard** [comment]
Oh, I'm sorry! Still rather new to puppet. Perhaps a dots-to-underscores transform, or similar,  might work.

**Comment by loomsen** [comment]
Hi Nick,

I guess that should work. Feel free to issue a pull request :+1:
